# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pipkin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='vorname',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='nachname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='person',
            name='aliasName',
            field=models.CharField(blank=True, max_length=100, verbose_name='Alias-Name der Person'),
        ),
        migrations.AddField(
            model_name='person',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Angelegt am'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Geändert am'),
        ),
    ]
