# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipkin', '0002_auto_20171126_1856'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='akdmTitle',
            field=models.CharField(blank=True, max_length=50, verbose_name='Akadem. Titel'),
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(default=datetime.date(1900, 1, 1), verbose_name='Geburtsdatum'),
        ),
        migrations.AddField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('M', 'männlich'), ('F', 'weiblich'), ('X', 'inter')], default='X', max_length=1, verbose_name='Geschlect'),
        ),
        migrations.AlterField(
            model_name='person',
            name='aliasName',
            field=models.CharField(blank=True, max_length=100, verbose_name='Alias-Name'),
        ),
        migrations.AlterField(
            model_name='person',
            name='firstname',
            field=models.CharField(max_length=100, verbose_name='Vorname'),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nachname'),
        ),
    ]
