# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-26 21:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipkin', '0004_auto_20171126_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addressLine', models.CharField(max_length=100, verbose_name='Adresse')),
                ('addressType', models.CharField(choices=[('M', 'Hauptadresse'), ('S', 'Nebenadresse')], default='M', max_length=1, verbose_name='Type')),
                ('zipCode', models.CharField(max_length=6, verbose_name='PLZ')),
                ('city', models.CharField(max_length=30, verbose_name='Ort')),
                ('country', models.CharField(blank=True, max_length=50, verbose_name='Land')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipkin.Person')),
            ],
        ),
    ]
