# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-01 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipkin', '0005_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contactSeverity', models.CharField(choices=[('M', 'Hauptkontakt'), ('S', 'Nebenkontakt'), ('E', 'Notfallskontakt')], default='M', max_length=1, verbose_name='Dringlichkeit')),
                ('contactType', models.CharField(choices=[('M', 'Hauptkontakt'), ('S', 'Nebenkontakt'), ('E', 'Notfallskontakt')], default='M', max_length=1, verbose_name='Type')),
                ('contactData', models.CharField(max_length=200, verbose_name='Kontaktdaten')),
                ('spaContact', models.BooleanField(default=False, verbose_name='SPA Kontak')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='sv',
            field=models.IntegerField(blank=True, default=0, verbose_name='SV#'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='sex',
            field=models.CharField(choices=[('M', 'männlich'), ('F', 'weiblich'), ('X', 'inter')], default='X', max_length=1, verbose_name='Geschlecht'),
        ),
        migrations.AddField(
            model_name='contact',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pipkin.Person'),
        ),
    ]
