# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-02 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipkin', '0006_auto_20171201_1810'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=50, verbose_name='Tag')),
                ('tagCategory', models.CharField(max_length=50, verbose_name='Kategorie')),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='telefon',
            field=models.CharField(blank=True, max_length=15, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactSeverity',
            field=models.CharField(choices=[('M', 'Hauptkontakt'), ('S', 'Nebenkontakt'), ('E', 'Notfallskontakt')], default='M', help_text='Zeigt die Relevanz des Kontakts', max_length=1, verbose_name='Dringlichkeit'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='contactType',
            field=models.CharField(choices=[('M', 'Email'), ('P', 'Telefon')], default='M', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, max_length=50, verbose_name='Email'),
        ),
    ]
